#
# Module manifest for module azure.databricks.cicd.tools'
#
# Generated by: Richie Lee
#
# Generated on: 06/01/2020
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'adls2.folder.access.tools.psm1'

    # Version number of this module.
    ModuleVersion = '0.0.0'

    # ID used to uniquely identify this module
    GUID = 'c2aa2c78-cb62-4d4e-93b1-151e8b549e55'

    # Author of this module
    Author = "Richie Lee"

    # Company or vendor of this module
    CompanyName = 'Sabin Ltd'

    # Copyright statement for this module
    Copyright = 'Sabin Ltd 2020'

    # Description of the functionality provided by this module
    Description = 'PowerShell module to help with granting Azure Active Directory Groups to have specific access (read/write) to folders in an Azure Data Lake.'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.0'

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @('')

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = 'path.ps1xml'

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module
    FunctionsToExport = 'New-FatDataLake', 'Set-FatAdlsAccess', "Get-FatDataLake",
                        'Get-FatAdlsAccessIntoCsv', 'Get-FatCsvAsArray','Get-FatAzConnection'

    # Cmdlets to export from this module
    CmdletsToExport = '*'

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module
    AliasesToExport = '*'

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
        PSData = @{
            Prerelease = 'preview'
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @("DataLake", "Azure", "DevOps", "Security")

            # A URL to the license for this module.
            # LicenseUri = ''

            # A URL to the main website for this project.
            #ProjectUri = 'https://github.com/sabinio/adls2.folder.access.tools'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = ''

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    #HelpInfoURI = 'https://github.com/sabinio/adls2.folder.access.tools'

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

    }
